name: bockaire
description: "Shipping Optimizer - Smart China to Germany shipment planning"
publish_to: 'none'

version: 0.8.5+16

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flex_color_scheme: ^8.0.2
  country_flags: ^3.0.2
  google_fonts: ^6.1.0

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  equatable: ^2.0.5

  # Routing
  go_router: ^14.6.2

  # Database
  drift: ^2.20.3
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.5
  path: ^1.9.0

  # Dependency Injection
  get_it: ^8.0.3

  # PDF Generation
  pdf: ^3.11.1
  printing: ^5.13.4

  # HTTP & AI
  dio: ^5.7.0
  google_generative_ai: ^0.4.6
  http: ^1.2.0
  openai_dart: ^0.5.0

  # Audio
  record: ^6.1.2

  # Image
  image_picker: ^1.0.7

  # Utils
  intl: ^0.20.2
  uuid: ^4.5.1
  logger: ^2.4.0
  flutter_dotenv: ^5.2.1
  package_info_plus: ^8.1.0
  shared_preferences: ^2.3.4

  # Modal Sheets
  wolt_modal_sheet: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code Generation
  drift_dev: ^2.20.3
  build_runner: ^2.5.4
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.2

  # Testing
  mocktail: ^1.0.4
  mockito: ^5.4.6

  # App Icon Generator
  flutter_launcher_icons: ^0.14.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

# App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: true
  macos:
    generate: true
    image_path: "assets/images/bockarie_logo_cropped.png"
  image_path: "assets/images/bockarie_logo_cropped.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/bockarie_logo_cropped.png"
